---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/guesses":
    post:
      summary: create guess
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - lat
              - lng
              properties:
                lat:
                  type: number
                lng:
                  type: number
        required: true
  "/users":
    post:
      summary: create user
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - name
              properties:
                email:
                  type: string
                name:
                  type: string
        required: true
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
  "/winners":
    get:
      summary: show winners
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
consumes:
- application/json
produces:
- application/json
